export default [
  {
    id: "1",
    address: "Karagandy Erubaeva 34",
    city: "Karagandy",
    postCode: 34090,
    country: "Kazakhstan",
    clientName: "Alexey",
    clientEmail: "alexey@gmail.com",
    clientAddress: "Abylai Khan 34",
    clientCity: "Almaty",
    clientPostCode: 34050,
    clientCountry: "Kazakhstan",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: "fourteen",
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
      {
        name: "Website Design",
        quantity: 1,
        price: 2600,
        total: 2600,
      },
    ],
    totalPrice: 6200,
    status: "Draft",
  },
  {
    id: "2",
    address: "Karagandy Erubaeva 34",
    city: "Karagandy",
    postCode: 34090,
    country: "Kazakhstan",
    clientName: "John",
    clientEmail: "john@gmail.com",
    clientAddress: "Nur-Sultan Abai 51",
    clientCity: "Nur-Sultan",
    clientPostCode: 31290,
    clientCountry: "Kazakhstan",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: "fourteen",
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
    ],
    totalPrice: 6200,
    status: "Pending",
  },
  {
    id: "3",
    address: "Karagandy Erubaeva 34",
    city: "Karagandy",
    postCode: 34090,
    country: "Kazakhstan",
    clientName: "Jane",
    clientEmail: "jane@gmail.com",
    clientAddress: "Emek 20",
    clientCity: "Ankara",
    clientPostCode: 34050,
    clientCountry: "Turkey",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: "fourteen",
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
      {
        name: "Website Design",
        quantity: 1,
        price: 2600,
        total: 2600,
      },
    ],
    totalPrice: 6200,
    status: "Paid",
  },
  {
    id: "4",
    address: "Karagandy Erubaeva 34",
    city: "Karagandy",
    postCode: 34090,
    country: "Kazakhstan",
    clientName: "Fred",
    clientEmail: "fred@gmail.com",
    clientAddress: "Hackney 198.St.",
    clientCity: "London",
    clientPostCode: 54632,
    clientCountry: "UK",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: "fourteen",
    projectDesc: "Website Design",
    projects: [
      {
        name: "Logo Design",
        quantity: 2,
        price: 1800,
        total: 3600,
      },
      {
        name: "Website Design",
        quantity: 1,
        price: 2600,
        total: 2600,
      },
    ],
    totalPrice: 6200,
    status: "Paid",
  },
  {
    id: "5",
    address: "Karagandy Erubaeva 34",
    city: "Karagandy",
    postCode: 34090,
    country: "Kazakhstan",
    clientName: "Vlad",
    clientEmail: "vladislav13@gmail.com",
    clientAddress: "Lenin 41",
    clientCity: "Moscow",
    clientPostCode: 34050,
    clientCountry: "Russia",
    invoiceDate: "2021-12-07",
    invoiceDue: "2021-12-21",
    paymentTerm: "fourteen",
    projectDesc: "Brand Creation",
    projects: [
      {
        name: "Advertisement",
        quantity: 2,
        price: 1900,
        total: 3800,
      },
      {
        name: "Google Ads",
        quantity: 1,
        price: 2000,
        total: 2000,
      },
    ],
    totalPrice: 5800,
    status: "Pending",
  },
];
